version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: todo-postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    networks:
      - todo-network
    restart: unless-stopped

  # Backend Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-backend
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://todo_user:todo_password@postgres:5432/todo_db
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - todo-network
    restart: unless-stopped
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma db push &&
        npm start
      "

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge 