version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: todo-frontend:latest
    container_name: ${DOCKER_CONTAINER_NAME:-todo-frontend}
    restart: unless-stopped
    ports:
      - "${DOCKER_PORT:-3000}:3000"
    networks:
      - ${DOCKER_NETWORK_NAME:-backend_todo-network}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - VITE_APP_ENV=${VITE_APP_ENV:-production}
      - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3001}
      - VITE_API_TIMEOUT=${VITE_API_TIMEOUT:-10000}
      - VITE_DEV_MODE=${VITE_DEV_MODE:-false}
      - VITE_ENABLE_DEVTOOLS=${VITE_ENABLE_DEVTOOLS:-false}
      - VITE_ENABLE_METRICS=${VITE_ENABLE_METRICS:-true}
      - VITE_METRICS_ENDPOINT=${VITE_METRICS_ENDPOINT:-/metrics}
    deploy:
      resources:
        limits:
          cpus: ${DOCKER_CPU_LIMIT:-0.5}
          memory: ${DOCKER_MEMORY_LIMIT:-512m}
        reservations:
          cpus: ${DOCKER_CPU_SHARES:-0.25}
          memory: ${DOCKER_MEMORY_RESERVATION:-256m}
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: ${HEALTH_CHECK_START_PERIOD:-30s}
    user: "${DOCKER_UID:-101}:${DOCKER_GID:-101}"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "app.environment=production"
      - "app.version=${VITE_APP_VERSION:-1.0.0}"

networks:
  ${DOCKER_NETWORK_NAME:-backend_todo-network}:
    external: true
    name: ${DOCKER_NETWORK_NAME:-backend_todo-network} 